### ISSUE TITLE
Fix hReview backcompat for summary property

### ISSUE THREAD

**Issue by gRegorLove** [indieweb/php-mf2#116]
> summary parse as p-name

Parsing https://w7apk.com/kenwood-th-d74a (with the latest master of php-mf2) should upgrade the "summary" property to "name".

http://microformats.org/wiki/h-review#Parser_Compatibility
https://chat.indieweb.org/microformats/2017-05-01#t1493670785338000
https://chat.indieweb.org/microformats/2017-03-13#t1489429297934000

**Comment by aaronpk** [comment]
Fixed in #146
