### ISSUE TITLE
Fix dependency on microformats/tests

### ISSUE THREAD

**Issue by aaronpk** [indieweb/php-mf2#122]
The 0.3.1 release relies on finding the microformats/tests repo by its git URL rather than looking it up from packagist. Instead this should reference the packagist version of the library, and only as a dev dependency. I'll fix this as soon as microformats/tests is published on packagist.

**Comment by aaronpk** [comment]
`mf2/tests` is now on packagist! https://packagist.org/packages/mf2/tests

**Comment by jkphl** [comment]
Yay! So now there's only another php-mf2 release missing. Maybe you could consider #121 to go into that as well?

**Comment by aaronpk** [comment]
This has been resolved in the [v0.3.2 release](https://github.com/indieweb/php-mf2/releases/tag/v0.3.2)!
