### ISSUE TITLE
Properties of empty array not empty object?

### ISSUE THREAD

**Issue by singpolyma** [indieweb/php-mf2#171]
https://pin13.net/mf2/?url=https%3A%2F%2Fsingpolyma.net%2F2018%2F04%2Fthoughts-after-ccsummit%2F

I would expect the `h-feed` to have `"properties": {}`

**Comment by Zegnat** [comment]
I agree. Will try and PR this today!

**Comment by aaronpk** [comment]
Fixed on the dev copy of pin13.net! https://pin13.net/mf2-dev/?url=https%3A%2F%2Fsingpolyma.net%2F2018%2F04%2Fthoughts-after-ccsummit%2F
