### ISSUE TITLE
Relative URL parsing code doesn’t handle protocol-relative URLs

### ISSUE THREAD

**Issue by barnabywalters** [indieweb/php-mf2#35]
E.G. `<a class="u-url" href="//domain.com/">` on http://example.com/page.html gets resolved to `http://example.com/page.html//domain.com/`

cc @aaronpk

**Comment by aaronpk** [comment]
My suggestion to resolve this is to require PHP 5.4 since 5.3 was declared unsupported in August 2014. http://php.net/eol.php

**Comment by jonnybarnes** [comment]
PHP5.4 is also EOL now.

**Comment by aaronpk** [comment]
ha! Well it seems safe to require a min of 5.4 then. Any objection, @barnabywalters? I would also be curious to hear from @benwerd if he thinks that would be okay.

**Comment by jonnybarnes** [comment]
Well, looking at the most recent commit there was one single test error that occurred in 5.4, if it were up to me I’d drop 5.4 support, unless someone can be bothered to fix said bug: https://travis-ci.org/indieweb/php-mf2/jobs/103192590

**Comment by aaronpk** [comment]
Just for the record, I've updated the test suite so that failure is passing now in 5.4. See https://github.com/aaronpk/php-mf2/commit/bfe4a0af9ef563c575fea2feac86e1ea120de053

**Comment by barnabywalters** [comment]
I’m happy requiring a minimum of PHP 5.4 as of the next release. The current version of the parser works well enough for anyone forced to use PHP 5.3.

**Comment by gRegorLove** [comment]
I think this can be closed now?

**Comment by aaronpk** [comment]
Yep! Looks like we're requiring 5.4 now.
