### ISSUE TITLE
Strip out leading and trailing spaces in u-* properties

### ISSUE THREAD

**Issue by barnabywalters** [indieweb/php-mf2#40]
As per https://twitter.com/jkphl/status/424165079664578560 and http://developers.whatwg.org/urls.html#valid-url-potentially-surrounded-by-spaces, when parsed as URLs (i.e. relative URL resolution is done) u-* properties should have leading and trailing spaces stripped.

**Comment by aaronpk** [comment]
This is fixed by #74
