### ISSUE TITLE
Not all h-feeds are found

### ISSUE THREAD

**Issue by jonnybarnes** [indieweb/php-mf2#55]
As can be seen in the following gists:

* real site waterpigs.co.uk, no h-feed found, https://gist.github.com/jonnybarnes/4ddf5606867db75fb0f0
* very simply html, h-feed found, https://gist.github.com/jonnybarnes/61a2bc9e360b12d53b1f

**Comment by gRegorLove** [comment]
This should be fixed as of #54 being merged.

**Comment by aaronpk** [comment]
Looks like it!
