### ISSUE TITLE
p-name property overly aggressive in removing whitespace between elements

### ISSUE THREAD

**Issue by kylewm** [indieweb/php-mf2#61]
```
<div class="h-entry">
  <data class="p-rsvp" value="yes">I'm attending</data>
  <a class="u-in-reply-to" href="https://snarfed.org/2014-06-16_homebrew-website-club-at-quip">Homebrew Website Club at Quip</a>
  <div class="p-content">Thanks for hosting!</div>
</div>
```

generates the p-name:
```
"I'm attendingHomebrew Website Club at Quip\n      Thanks for hosting!"
```

**Comment by gRegorLove** [comment]
This appears to be how PHP's DomElement::nodeValue returns the value, not additional whitespace trimming. I'm still looking into alternatives that don't entail traversing each element to get their value and then assembling the name, but that might be the only way to do it.

**Comment by barnabywalters** [comment]
Thanks for raising this issue and looking into it! I have done some experimenting and determined the cause of the problem. PHP’s DOMDocument is mistreating whitespace specifically adjacent to any elements it doesn’t recognise, such as HTML5/living standard elements like `<data>` and silly made up elements like `<the-floor-is-made-of-lava>`. To demonstrate:

```php
<?php

function test($h) {
   $doc = new DOMDocument();
   $doc->loadHTML($h);
   // loadHTML inserts <html> and <body> elements automatically.
   return $doc->documentElement->firstChild->firstChild->textContent;
}

$working = <<<EOT
<div class="h-entry">
  <span class="p-rsvp" value="yes">I'm attending</span>
  <a class="u-in-reply-to" href="https://snarfed.org/2014-06-16_homebrew-website-club-at-quip">Homebrew Website Club at Quip</a>
</div>
EOT;

$nonWorking = <<<EOT
<div class="h-entry">
  <data class="p-rsvp" value="yes">I'm attending</data>
  <a class="u-in-reply-to" href="https://snarfed.org/2014-06-16_homebrew-website-club-at-quip">Homebrew Website Club at Quip</a>
</div>
EOT;

echo test($working);
echo test($nonWorking);
```
produces

```
"\n  I'm attending\n  Homebrew Website Club at Quip\n"
```

and 

```
"\n  I'm attendingHomebrew Website Club at Quip\n"
```

As for how best so solve this, I have done some experimentation. The IE CSS javascript trick of creating but not appending unrecognised elements didn’t work (hey, it was worth a try). Sometimes stupid bugs require stupid solutions, and the best I can think of right now is to document the HTML5 elements which DOMDocument doesn’t support correctly and append `<span />` after each instance of all of them. I’ve confirmed that this solves the whitespace problem:

```php
echo test(<<<EOT
<div class="h-entry">
  <data class="p-rsvp" value="yes">I'm attending</data><span />
  <a class="u-in-reply-to" href="https://snarfed.org/2014-06-16_homebrew-website-club-at-quip">Homebrew Website Club at Quip</a>
</div>
EOT
);
```

produces the correctly parsed

```
"\n  I'm attending\n  Homebrew Website Club at Quip\n  Thanks for hosting!\n"
```

Unless anyone has a more elegant solution, I’m going to go ahead and build this.

**Comment by barnabywalters** [comment]
Archived from discussion in #indiewebcamp:

* using htmltidy probably isn’t an option due to requiring an additional dependency which doesn’t support HTML5 (at least without significant config changes and post-processing hacks)
* Simply changing all `<data>` etc. elements to `<div>` or `<span>` also isn’t an option as the parsing algorithm makes use of element tag names.

**Comment by gRegorLove** [comment]
To clarify, I would only suggest changing the elements in the `parseH` function, and only if it comes after any other parsing that might rely on the element names (I think it does, but I'm not sure). In my debugging so far, it seems like it's only at this line where we might need to transform elements: https://github.com/indieweb/php-mf2/blob/master/Mf2/Parser.php#L808

**Comment by aaronpk** [comment]
Here's a test case to add:

```php
	public function testWhitespaceBetweenElements() {
		$input = <<<EOT
<div class="h-entry">
  <data class="p-rsvp" value="yes">I'm attending</data>
  <a class="u-in-reply-to" href="https://snarfed.org/2014-06-16_homebrew-website-club-at-quip">Homebrew Website Club at Quip</a>
  <div class="p-content">Thanks for hosting!</div>
</div>
EOT;

		$parser = new Parser($input);
		$output = $parser->parse();

		$this->assertContains('h-entry', $output['items'][0]['type']);
		$this->assertContains('I\'m attending Homebrew Website Club at Quip', $output['items'][0]['properties']['name'][0]);
	}
```

**Comment by barnabywalters** [comment]
I fixed this issue for data elements as that’s the only element we currently have real-world examples of problems with. As we find more elements which cause problems they can be added to the `$unsupportedTags` array, and will have spaces appended after them when being used to parse implied names.
