### ISSUE TITLE
Fix implied value for nested h-* microformats

### ISSUE THREAD

**Issue by gRegorLove** [indieweb/php-mf2#70]
From http://microformats.org/wiki/microformats2-parsing##child%20element%20itself%20has%20a%20microformat

>- parse a child element for microformats (recurse)
>  - if that child element itself has a microformat ("h-*" or backcompat roots) and is a property element, add it into the array of values for that property as a { } structure, add to that { } structure:
>    - value:
>      - if it's a p-* property element, use the first p-name of the h-* child
>       - else if it's an e-* property element, re-use its { } structure with existing value: inside.
>       - else if it's a u-* property element and the h-* child has a u-url, use the first such u-url
>       - else use the parsed property value per p-*,u-*,dt-* parsing respectively 

See also: 
- http://microformats.org/wiki/microformats2-parsing-brainstorming#Nested_h-.2A_objects.27_.22value.22_property
- http://logs.glob.uno/?c=freenode%23microformats&s=1+Jul+2015&e=1+Jul+2015&h=php-mf2#c81960

**Comment by gRegorLove** [comment]
I intend to take a crack at this one.

**Comment by tantek** [comment]
Great!

**Comment by barnabywalters** [comment]
@gRegorLove Unless I am very much mistaken, I implemented these changes in the last release. When making issues, please check that it is actually an issue :)

The relevant test cases are here: https://github.com/indieweb/php-mf2/blob/master/tests/Mf2/CombinedMicroformatsTest.php#L224 — if you find php-mf2 to deviate from the spec somewhere then go ahead and re-open a separate issue for that.

The latest version is live at https://waterpigs.co.uk/php-mf2/ and the behaviour can be confirmed and tested there.

**Comment by gRegorLove** [comment]
Thanks, @barnabywalters! You're fast. :) I didn't even notice there was a new release.

**Comment by barnabywalters** [comment]
Ha ha ha, I haven’t been very fast lately so I understand assuming it wasn’t done :) And I forgot to announce the new release for some reason, thanks for the reminder!

**Comment by aaronpk** [comment]
@barnabywalters @gRegorLove it looks like the parser doesn't handle this properly after all. I added a test case demonstrating the failure.

**Comment by gRegorLove** [comment]
I'll defer to @barnabywalters, unless he's busy and may not be able to get to it soon. Just let me know.

**Comment by barnabywalters** [comment]
I’m a little preoccupied moving house, workshop and country right now, so if someone else wants to take on this issue then they do so with my blessing and appreciation :)
