### ISSUE TITLE
Proposal: change license from MIT to Public Domain / CC0

### ISSUE THREAD

**Issue by veganstraightedge** [indieweb/php-mf2#76]
To match the [https://indiewebcamp.com](IndieWebCamp wiki)'s content license and the license of other indieweb softwares (https://github.com/indieweb/microformats2-ruby#license).

**Comment by veganstraightedge** [comment]
@barnabywalters

**Comment by barnabywalters** [comment]
In principle I’m very happy to make this change, seeing as CC state that CC0 is “acceptable” for software (https://wiki.creativecommons.org/index.php/Frequently_Asked_Questions#Can_I_apply_a_Creative_Commons_license_to_software.3F).
