### ISSUE TITLE
Implied photo

### ISSUE THREAD

**Issue by gRegorLove** [indieweb/php-mf2#88]
[Implied photo parsing](http://microformats.org/wiki/microformats2-parsing#parsing_for_implied_properties) is not working for at least this case:

> else if .h-x>:only-child>img[src]:only-of-type:not[.h-*] then use that img src for photo

Need to fix and test for all implied photo cases.

Example:
- http://pin13.net/mf2/?url=https%3A%2F%2Findiewebcamp.com%2FUser%3ATantek.com
- vs. http://glennjones.net/tools/microformats/?url=https%3A%2F%2Findiewebcamp.com%2FUser%3ATantek.com&callback=&dateformat=auto

Chat log: https://indiewebcamp.com/irc/2016-04-08#t1460150630108

**Comment by aaronpk** [comment]
This appears to be fixed, yes?

**Comment by gRegorLove** [comment]
Fixed and merged, yep.
