### ISSUE TITLE
Parsing "value" for nested microformat when it's not a property

### ISSUE THREAD

**Issue by gRegorLove** [indieweb/php-mf2#98]
Per http://microformats.org/wiki/microformats2-parsing##if+that+child+element+itself+has+a+microformat, a nested microformat should only add a "value" if it is also a property element.

Sample: `<div class="h-card" ><a class="h-card" href="jane.html">Jane Doe</a><p></p></div>`

Expected output:

```
{
    "items": [{
        "type": ["h-card"],
        "properties": {
            "name": ["Jane Doe"]
        },
        "children": [{
            "type": ["h-card"],
            "properties": {
                "name": ["Jane Doe"],
                "url": ["jane.html"]
            }
        }]
    }],
    "rels": {},
    "rel-urls": {}
}
```

mf2py handles this, but php-mf2 and microformats-shiv do not.

Discussion: http://logs.glob.uno/?c=freenode%23microformats&s=10+May+2016&e=10+May+2016#c87112

**Comment by aaronpk** [comment]
Alternate chat log URL: https://chat.indieweb.org/microformats/2016-05-10#t1462911536364000
